apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\BJIT\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: api-service
  name: api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\BJIT\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/practice-boot-api-network: "true"
        io.kompose.service: api-service
    spec:
      containers:
        - env:
            - name: SERVICE_NAME
              value: spring_boot_service
            - name: SERVICE_TAGS
              value: dev
            - name: SPRING_DATASOURCE_PASSWORD
              value: "123456"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mariadb://db-service:3306/practice_spring_boot
            - name: SPRING_DATASOURCE_USERNAME
              value: saiful_sohel
          image: api-service:v1
          name: spring-boot-service-container
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
